import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapClient from "@/src/components/BootstrapClient";
import Sidebar from "@/app/components/Sidebar";
import Topbar from "@/app/components/Topbar";
import {Col, Container, Row} from "react-bootstrap";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Container>
          <Row className="justify-content-md-center">
            <Col >
              <Topbar />
            </Col>
          </Row>
          <Row>
            <Col md="2">
              <Sidebar />
            </Col>
            <Col className="bg-light-subtle text-md-center">
              {children}
            </Col>
          </Row>
        </Container>
        <BootstrapClient />
      </body>
    </html>
  );
}
